name: Run quality checks

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[ci]"

      - name: Check sentence casing
        run: poe check-sentence-casing

      - name: Check options
        run: poe check-options
