name: Run quality checks

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: 'checks ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: |
          uv sync --all-extras --python 3.9

      - name: Check sentence casing
        run: |
          source .venv/bin/activate
          poe check-sentence-casing

      - name: Check options
        run: |
          source .venv/bin/activate
          poe check-options
