name: Run quality checks

# on all branches
on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[ci]"

      - name: Check sentence casing
        run: |
          poe check-sentence-casing

      - name: Check options
        run: |
          poe check-options
